/* © Copyright Piotr Nikiel, CERN, 2015.  All rights not expressly granted are reserved.
 *
 *  Created on: 15 Nov,  2015
 *      Author: Piotr Nikiel <piotr@nikiel.info>
 *
 *  This file is part of Quasar.
 *
 *  Quasar is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public Licence as published by
 *  the Free Software Foundation, either version 3 of the Licence.
 *
 *  Quasar is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public Licence for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with Quasar.  If not, see <http://www.gnu.org/licenses/>.
 */



#ifndef __STATUSCODE_H__
#define __STATUSCODE_H__

#include <open62541.h>
#include <uastring.h>
#include <opcua_platformdefs.h>
#include <vector>

#define OpcUa_Good UA_STATUSCODE_GOOD
#define OpcUa_Bad  0x80000000
#define OpcUa_Uncertain 0x40000000
#define OpcUa_BadNotImplemented UA_STATUSCODE_BADNOTIMPLEMENTED
#define OpcUa_BadNoData UA_STATUSCODE_BADNODATA
#define OpcUa_BadDataEncodingInvalid UA_STATUSCODE_BADDATAENCODINGINVALID
#define OpcUa_BadDataUnavailable UA_STATUSCODE_BADDATAUNAVAILABLE
#define OpcUa_BadInvalidArgument UA_STATUSCODE_BADINVALIDARGUMENT
#define OpcUa_BadWaitingForInitialData UA_STATUSCODE_BADWAITINGFORINITIALDATA
#define OpcUa_BadOutOfRange UA_STATUSCODE_BADOUTOFRANGE
#define OpcUa_BadUserAccessDenied UA_STATUSCODE_BADUSERACCESSDENIED
#define OpcUa_BadNoCommunication UA_STATUSCODE_BADNOCOMMUNICATION
#define OpcUa_BadCommunicationError UA_STATUSCODE_BADCOMMUNICATIONERROR
#define OpcUa_BadNotSupported UA_STATUSCODE_BADNOTSUPPORTED
#define OpcUa_BadResourceUnavailable UA_STATUSCODE_BADRESOURCEUNAVAILABLE
#define OpcUa_BadOutOfService UA_STATUSCODE_BADOUTOFSERVICE
#define OpcUa_BadNotReadable UA_STATUSCODE_BADNOTREADABLE
#define OpcUa_BadNotWritable UA_STATUSCODE_BADNOTWRITABLE
#define OpcUa_BadInternalError UA_STATUSCODE_BADINTERNALERROR
#define OpcUa_BadInvalidState UA_STATUSCODE_BADINVALIDSTATE
#define OpcUa_UncertainInitialValue UA_STATUSCODE_UNCERTAININITIALVALUE
#define OpcUa_BadUnexpectedError UA_STATUSCODE_BADUNEXPECTEDERROR
#define OpcUa_BadParentNodeIdInvalid UA_STATUSCODE_BADPARENTNODEIDINVALID
#define OpcUa_BadServerNotConnected UA_STATUSCODE_BADSERVERNOTCONNECTED
#define OpcUa_BadIndexRangeInvalid UA_STATUSCODE_BADINDEXRANGEINVALID
#define OpcUa_BadIndexRangeNoData UA_STATUSCODE_BADINDEXRANGENODATA
#define OpcUa_BadArgumentsMissing UA_STATUSCODE_BADARGUMENTSMISSING
#define OpcUa_BadConnectionClosed UA_STATUSCODE_BADCONNECTIONCLOSED


/* Complete status-code alias set, generated from the stack's UA_StatusCode_name table
 * (UASDK defines all OpcUa_* codes; partial aliasing kept breaking production servers) */
#define OpcUa_BadAggregateConfigurationRejected UA_STATUSCODE_BADAGGREGATECONFIGURATIONREJECTED
#define OpcUa_BadAggregateInvalidInputs UA_STATUSCODE_BADAGGREGATEINVALIDINPUTS
#define OpcUa_BadAggregateListMismatch UA_STATUSCODE_BADAGGREGATELISTMISMATCH
#define OpcUa_BadAggregateNotSupported UA_STATUSCODE_BADAGGREGATENOTSUPPORTED
#define OpcUa_BadAlreadyExists UA_STATUSCODE_BADALREADYEXISTS
#define OpcUa_BadApplicationSignatureInvalid UA_STATUSCODE_BADAPPLICATIONSIGNATUREINVALID
#define OpcUa_BadAttributeIdInvalid UA_STATUSCODE_BADATTRIBUTEIDINVALID
#define OpcUa_BadBoundNotFound UA_STATUSCODE_BADBOUNDNOTFOUND
#define OpcUa_BadBoundNotSupported UA_STATUSCODE_BADBOUNDNOTSUPPORTED
#define OpcUa_BadBrowseDirectionInvalid UA_STATUSCODE_BADBROWSEDIRECTIONINVALID
#define OpcUa_BadBrowseNameDuplicated UA_STATUSCODE_BADBROWSENAMEDUPLICATED
#define OpcUa_BadBrowseNameInvalid UA_STATUSCODE_BADBROWSENAMEINVALID
#define OpcUa_BadCertificateChainIncomplete UA_STATUSCODE_BADCERTIFICATECHAININCOMPLETE
#define OpcUa_BadCertificateHostNameInvalid UA_STATUSCODE_BADCERTIFICATEHOSTNAMEINVALID
#define OpcUa_BadCertificateInvalid UA_STATUSCODE_BADCERTIFICATEINVALID
#define OpcUa_BadCertificateIssuerRevocationUnknown UA_STATUSCODE_BADCERTIFICATEISSUERREVOCATIONUNKNOWN
#define OpcUa_BadCertificateIssuerRevoked UA_STATUSCODE_BADCERTIFICATEISSUERREVOKED
#define OpcUa_BadCertificateIssuerTimeInvalid UA_STATUSCODE_BADCERTIFICATEISSUERTIMEINVALID
#define OpcUa_BadCertificateIssuerUseNotAllowed UA_STATUSCODE_BADCERTIFICATEISSUERUSENOTALLOWED
#define OpcUa_BadCertificatePolicyCheckFailed UA_STATUSCODE_BADCERTIFICATEPOLICYCHECKFAILED
#define OpcUa_BadCertificateRevocationUnknown UA_STATUSCODE_BADCERTIFICATEREVOCATIONUNKNOWN
#define OpcUa_BadCertificateRevoked UA_STATUSCODE_BADCERTIFICATEREVOKED
#define OpcUa_BadCertificateTimeInvalid UA_STATUSCODE_BADCERTIFICATETIMEINVALID
#define OpcUa_BadCertificateUntrusted UA_STATUSCODE_BADCERTIFICATEUNTRUSTED
#define OpcUa_BadCertificateUriInvalid UA_STATUSCODE_BADCERTIFICATEURIINVALID
#define OpcUa_BadCertificateUseNotAllowed UA_STATUSCODE_BADCERTIFICATEUSENOTALLOWED
#define OpcUa_BadConditionAlreadyDisabled UA_STATUSCODE_BADCONDITIONALREADYDISABLED
#define OpcUa_BadConditionAlreadyEnabled UA_STATUSCODE_BADCONDITIONALREADYENABLED
#define OpcUa_BadConditionAlreadyShelved UA_STATUSCODE_BADCONDITIONALREADYSHELVED
#define OpcUa_BadConditionBranchAlreadyAcked UA_STATUSCODE_BADCONDITIONBRANCHALREADYACKED
#define OpcUa_BadConditionBranchAlreadyConfirmed UA_STATUSCODE_BADCONDITIONBRANCHALREADYCONFIRMED
#define OpcUa_BadConditionDisabled UA_STATUSCODE_BADCONDITIONDISABLED
#define OpcUa_BadConditionNotShelved UA_STATUSCODE_BADCONDITIONNOTSHELVED
#define OpcUa_BadConfigurationError UA_STATUSCODE_BADCONFIGURATIONERROR
#define OpcUa_BadConnectionRejected UA_STATUSCODE_BADCONNECTIONREJECTED
#define OpcUa_BadContentFilterInvalid UA_STATUSCODE_BADCONTENTFILTERINVALID
#define OpcUa_BadContinuationPointInvalid UA_STATUSCODE_BADCONTINUATIONPOINTINVALID
#define OpcUa_BadDataEncodingUnsupported UA_STATUSCODE_BADDATAENCODINGUNSUPPORTED
#define OpcUa_BadDataLost UA_STATUSCODE_BADDATALOST
#define OpcUa_BadDataTypeIdUnknown UA_STATUSCODE_BADDATATYPEIDUNKNOWN
#define OpcUa_BadDeadbandFilterInvalid UA_STATUSCODE_BADDEADBANDFILTERINVALID
#define OpcUa_BadDecodingError UA_STATUSCODE_BADDECODINGERROR
#define OpcUa_BadDependentValueChanged UA_STATUSCODE_BADDEPENDENTVALUECHANGED
#define OpcUa_BadDeviceFailure UA_STATUSCODE_BADDEVICEFAILURE
#define OpcUa_BadDialogNotActive UA_STATUSCODE_BADDIALOGNOTACTIVE
#define OpcUa_BadDialogResponseInvalid UA_STATUSCODE_BADDIALOGRESPONSEINVALID
#define OpcUa_BadDisconnect UA_STATUSCODE_BADDISCONNECT
#define OpcUa_BadDiscoveryUrlMissing UA_STATUSCODE_BADDISCOVERYURLMISSING
#define OpcUa_BadDominantValueChanged UA_STATUSCODE_BADDOMINANTVALUECHANGED
#define OpcUa_BadDuplicateReferenceNotAllowed UA_STATUSCODE_BADDUPLICATEREFERENCENOTALLOWED
#define OpcUa_BadEncodingError UA_STATUSCODE_BADENCODINGERROR
#define OpcUa_BadEncodingLimitsExceeded UA_STATUSCODE_BADENCODINGLIMITSEXCEEDED
#define OpcUa_BadEndOfStream UA_STATUSCODE_BADENDOFSTREAM
#define OpcUa_BadEntryExists UA_STATUSCODE_BADENTRYEXISTS
#define OpcUa_BadEventFilterInvalid UA_STATUSCODE_BADEVENTFILTERINVALID
#define OpcUa_BadEventIdUnknown UA_STATUSCODE_BADEVENTIDUNKNOWN
#define OpcUa_BadEventNotAcknowledgeable UA_STATUSCODE_BADEVENTNOTACKNOWLEDGEABLE
#define OpcUa_BadExpectedStreamToBlock UA_STATUSCODE_BADEXPECTEDSTREAMTOBLOCK
#define OpcUa_BadFilterElementInvalid UA_STATUSCODE_BADFILTERELEMENTINVALID
#define OpcUa_BadFilterLiteralInvalid UA_STATUSCODE_BADFILTERLITERALINVALID
#define OpcUa_BadFilterNotAllowed UA_STATUSCODE_BADFILTERNOTALLOWED
#define OpcUa_BadFilterOperandCountMismatch UA_STATUSCODE_BADFILTEROPERANDCOUNTMISMATCH
#define OpcUa_BadFilterOperandInvalid UA_STATUSCODE_BADFILTEROPERANDINVALID
#define OpcUa_BadFilterOperatorInvalid UA_STATUSCODE_BADFILTEROPERATORINVALID
#define OpcUa_BadFilterOperatorUnsupported UA_STATUSCODE_BADFILTEROPERATORUNSUPPORTED
#define OpcUa_BadHistoryOperationInvalid UA_STATUSCODE_BADHISTORYOPERATIONINVALID
#define OpcUa_BadHistoryOperationUnsupported UA_STATUSCODE_BADHISTORYOPERATIONUNSUPPORTED
#define OpcUa_BadIdentityChangeNotSupported UA_STATUSCODE_BADIDENTITYCHANGENOTSUPPORTED
#define OpcUa_BadIdentityTokenInvalid UA_STATUSCODE_BADIDENTITYTOKENINVALID
#define OpcUa_BadIdentityTokenRejected UA_STATUSCODE_BADIDENTITYTOKENREJECTED
#define OpcUa_BadInsufficientClientProfile UA_STATUSCODE_BADINSUFFICIENTCLIENTPROFILE
#define OpcUa_BadInvalidSelfReference UA_STATUSCODE_BADINVALIDSELFREFERENCE
#define OpcUa_BadInvalidTimestamp UA_STATUSCODE_BADINVALIDTIMESTAMP
#define OpcUa_BadInvalidTimestampArgument UA_STATUSCODE_BADINVALIDTIMESTAMPARGUMENT
#define OpcUa_BadLicenseExpired UA_STATUSCODE_BADLICENSEEXPIRED
#define OpcUa_BadLicenseLimitsExceeded UA_STATUSCODE_BADLICENSELIMITSEXCEEDED
#define OpcUa_BadLicenseNotAvailable UA_STATUSCODE_BADLICENSENOTAVAILABLE
#define OpcUa_BadMaxAgeInvalid UA_STATUSCODE_BADMAXAGEINVALID
#define OpcUa_BadMaxConnectionsReached UA_STATUSCODE_BADMAXCONNECTIONSREACHED
#define OpcUa_BadMessageNotAvailable UA_STATUSCODE_BADMESSAGENOTAVAILABLE
#define OpcUa_BadMethodInvalid UA_STATUSCODE_BADMETHODINVALID
#define OpcUa_BadMonitoredItemFilterInvalid UA_STATUSCODE_BADMONITOREDITEMFILTERINVALID
#define OpcUa_BadMonitoredItemFilterUnsupported UA_STATUSCODE_BADMONITOREDITEMFILTERUNSUPPORTED
#define OpcUa_BadMonitoredItemIdInvalid UA_STATUSCODE_BADMONITOREDITEMIDINVALID
#define OpcUa_BadMonitoringModeInvalid UA_STATUSCODE_BADMONITORINGMODEINVALID
#define OpcUa_BadNoContinuationPoints UA_STATUSCODE_BADNOCONTINUATIONPOINTS
#define OpcUa_BadNoDataAvailable UA_STATUSCODE_BADNODATAAVAILABLE
#define OpcUa_BadNoDeleteRights UA_STATUSCODE_BADNODELETERIGHTS
#define OpcUa_BadNoEntryExists UA_STATUSCODE_BADNOENTRYEXISTS
#define OpcUa_BadNoMatch UA_STATUSCODE_BADNOMATCH
#define OpcUa_BadNoSubscription UA_STATUSCODE_BADNOSUBSCRIPTION
#define OpcUa_BadNoValidCertificates UA_STATUSCODE_BADNOVALIDCERTIFICATES
#define OpcUa_BadNodeAttributesInvalid UA_STATUSCODE_BADNODEATTRIBUTESINVALID
#define OpcUa_BadNodeClassInvalid UA_STATUSCODE_BADNODECLASSINVALID
#define OpcUa_BadNodeIdExists UA_STATUSCODE_BADNODEIDEXISTS
#define OpcUa_BadNodeIdInvalid UA_STATUSCODE_BADNODEIDINVALID
#define OpcUa_BadNodeIdRejected UA_STATUSCODE_BADNODEIDREJECTED
#define OpcUa_BadNodeIdUnknown UA_STATUSCODE_BADNODEIDUNKNOWN
#define OpcUa_BadNodeNotInView UA_STATUSCODE_BADNODENOTINVIEW
#define OpcUa_BadNonceInvalid UA_STATUSCODE_BADNONCEINVALID
#define OpcUa_BadNotConnected UA_STATUSCODE_BADNOTCONNECTED
#define OpcUa_BadNotExecutable UA_STATUSCODE_BADNOTEXECUTABLE
#define OpcUa_BadNotFound UA_STATUSCODE_BADNOTFOUND
#define OpcUa_BadNotTypeDefinition UA_STATUSCODE_BADNOTTYPEDEFINITION
#define OpcUa_BadNothingToDo UA_STATUSCODE_BADNOTHINGTODO
#define OpcUa_BadNumericOverflow UA_STATUSCODE_BADNUMERICOVERFLOW
#define OpcUa_BadObjectDeleted UA_STATUSCODE_BADOBJECTDELETED
#define OpcUa_BadOperationAbandoned UA_STATUSCODE_BADOPERATIONABANDONED
#define OpcUa_BadOutOfMemory UA_STATUSCODE_BADOUTOFMEMORY
#define OpcUa_BadProtocolVersionUnsupported UA_STATUSCODE_BADPROTOCOLVERSIONUNSUPPORTED
#define OpcUa_BadQueryTooComplex UA_STATUSCODE_BADQUERYTOOCOMPLEX
#define OpcUa_BadReferenceLocalOnly UA_STATUSCODE_BADREFERENCELOCALONLY
#define OpcUa_BadReferenceNotAllowed UA_STATUSCODE_BADREFERENCENOTALLOWED
#define OpcUa_BadReferenceTypeIdInvalid UA_STATUSCODE_BADREFERENCETYPEIDINVALID
#define OpcUa_BadRefreshInProgress UA_STATUSCODE_BADREFRESHINPROGRESS
#define OpcUa_BadRequestCancelledByClient UA_STATUSCODE_BADREQUESTCANCELLEDBYCLIENT
#define OpcUa_BadRequestCancelledByRequest UA_STATUSCODE_BADREQUESTCANCELLEDBYREQUEST
#define OpcUa_BadRequestHeaderInvalid UA_STATUSCODE_BADREQUESTHEADERINVALID
#define OpcUa_BadRequestInterrupted UA_STATUSCODE_BADREQUESTINTERRUPTED
#define OpcUa_BadRequestNotAllowed UA_STATUSCODE_BADREQUESTNOTALLOWED
#define OpcUa_BadRequestNotComplete UA_STATUSCODE_BADREQUESTNOTCOMPLETE
#define OpcUa_BadRequestTimeout UA_STATUSCODE_BADREQUESTTIMEOUT
#define OpcUa_BadRequestTooLarge UA_STATUSCODE_BADREQUESTTOOLARGE
#define OpcUa_BadRequestTypeInvalid UA_STATUSCODE_BADREQUESTTYPEINVALID
#define OpcUa_BadResponseTooLarge UA_STATUSCODE_BADRESPONSETOOLARGE
#define OpcUa_BadSecureChannelClosed UA_STATUSCODE_BADSECURECHANNELCLOSED
#define OpcUa_BadSecureChannelIdInvalid UA_STATUSCODE_BADSECURECHANNELIDINVALID
#define OpcUa_BadSecureChannelTokenUnknown UA_STATUSCODE_BADSECURECHANNELTOKENUNKNOWN
#define OpcUa_BadSecurityChecksFailed UA_STATUSCODE_BADSECURITYCHECKSFAILED
#define OpcUa_BadSecurityModeInsufficient UA_STATUSCODE_BADSECURITYMODEINSUFFICIENT
#define OpcUa_BadSecurityModeRejected UA_STATUSCODE_BADSECURITYMODEREJECTED
#define OpcUa_BadSecurityPolicyRejected UA_STATUSCODE_BADSECURITYPOLICYREJECTED
#define OpcUa_BadSemaphoreFileMissing UA_STATUSCODE_BADSEMAPHOREFILEMISSING
#define OpcUa_BadSensorFailure UA_STATUSCODE_BADSENSORFAILURE
#define OpcUa_BadSequenceNumberInvalid UA_STATUSCODE_BADSEQUENCENUMBERINVALID
#define OpcUa_BadSequenceNumberUnknown UA_STATUSCODE_BADSEQUENCENUMBERUNKNOWN
#define OpcUa_BadServerHalted UA_STATUSCODE_BADSERVERHALTED
#define OpcUa_BadServerIndexInvalid UA_STATUSCODE_BADSERVERINDEXINVALID
#define OpcUa_BadServerNameMissing UA_STATUSCODE_BADSERVERNAMEMISSING
#define OpcUa_BadServerUriInvalid UA_STATUSCODE_BADSERVERURIINVALID
#define OpcUa_BadServiceUnsupported UA_STATUSCODE_BADSERVICEUNSUPPORTED
#define OpcUa_BadSessionClosed UA_STATUSCODE_BADSESSIONCLOSED
#define OpcUa_BadSessionIdInvalid UA_STATUSCODE_BADSESSIONIDINVALID
#define OpcUa_BadSessionNotActivated UA_STATUSCODE_BADSESSIONNOTACTIVATED
#define OpcUa_BadShelvingTimeOutOfRange UA_STATUSCODE_BADSHELVINGTIMEOUTOFRANGE
#define OpcUa_BadShutdown UA_STATUSCODE_BADSHUTDOWN
#define OpcUa_BadSourceNodeIdInvalid UA_STATUSCODE_BADSOURCENODEIDINVALID
#define OpcUa_BadStateNotActive UA_STATUSCODE_BADSTATENOTACTIVE
#define OpcUa_BadStructureMissing UA_STATUSCODE_BADSTRUCTUREMISSING
#define OpcUa_BadSubscriptionIdInvalid UA_STATUSCODE_BADSUBSCRIPTIONIDINVALID
#define OpcUa_BadSyntaxError UA_STATUSCODE_BADSYNTAXERROR
#define OpcUa_BadTargetNodeIdInvalid UA_STATUSCODE_BADTARGETNODEIDINVALID
#define OpcUa_BadTcpEndpointUrlInvalid UA_STATUSCODE_BADTCPENDPOINTURLINVALID
#define OpcUa_BadTcpInternalError UA_STATUSCODE_BADTCPINTERNALERROR
#define OpcUa_BadTcpMessageTooLarge UA_STATUSCODE_BADTCPMESSAGETOOLARGE
#define OpcUa_BadTcpMessageTypeInvalid UA_STATUSCODE_BADTCPMESSAGETYPEINVALID
#define OpcUa_BadTcpNotEnoughResources UA_STATUSCODE_BADTCPNOTENOUGHRESOURCES
#define OpcUa_BadTcpSecureChannelUnknown UA_STATUSCODE_BADTCPSECURECHANNELUNKNOWN
#define OpcUa_BadTcpServerTooBusy UA_STATUSCODE_BADTCPSERVERTOOBUSY
#define OpcUa_BadTicketInvalid UA_STATUSCODE_BADTICKETINVALID
#define OpcUa_BadTicketRequired UA_STATUSCODE_BADTICKETREQUIRED
#define OpcUa_BadTimeout UA_STATUSCODE_BADTIMEOUT
#define OpcUa_BadTimestampNotSupported UA_STATUSCODE_BADTIMESTAMPNOTSUPPORTED
#define OpcUa_BadTimestampsToReturnInvalid UA_STATUSCODE_BADTIMESTAMPSTORETURNINVALID
#define OpcUa_BadTooManyArguments UA_STATUSCODE_BADTOOMANYARGUMENTS
#define OpcUa_BadTooManyMatches UA_STATUSCODE_BADTOOMANYMATCHES
#define OpcUa_BadTooManyMonitoredItems UA_STATUSCODE_BADTOOMANYMONITOREDITEMS
#define OpcUa_BadTooManyOperations UA_STATUSCODE_BADTOOMANYOPERATIONS
#define OpcUa_BadTooManyPublishRequests UA_STATUSCODE_BADTOOMANYPUBLISHREQUESTS
#define OpcUa_BadTooManySessions UA_STATUSCODE_BADTOOMANYSESSIONS
#define OpcUa_BadTooManySubscriptions UA_STATUSCODE_BADTOOMANYSUBSCRIPTIONS
#define OpcUa_BadTransactionPending UA_STATUSCODE_BADTRANSACTIONPENDING
#define OpcUa_BadTypeDefinitionInvalid UA_STATUSCODE_BADTYPEDEFINITIONINVALID
#define OpcUa_BadTypeMismatch UA_STATUSCODE_BADTYPEMISMATCH
#define OpcUa_BadUnknownResponse UA_STATUSCODE_BADUNKNOWNRESPONSE
#define OpcUa_BadUserSignatureInvalid UA_STATUSCODE_BADUSERSIGNATUREINVALID
#define OpcUa_BadViewIdUnknown UA_STATUSCODE_BADVIEWIDUNKNOWN
#define OpcUa_BadViewParameterMismatch UA_STATUSCODE_BADVIEWPARAMETERMISMATCH
#define OpcUa_BadViewTimestampInvalid UA_STATUSCODE_BADVIEWTIMESTAMPINVALID
#define OpcUa_BadViewVersionInvalid UA_STATUSCODE_BADVIEWVERSIONINVALID
#define OpcUa_BadWaitingForResponse UA_STATUSCODE_BADWAITINGFORRESPONSE
#define OpcUa_BadWouldBlock UA_STATUSCODE_BADWOULDBLOCK
#define OpcUa_BadWriteNotSupported UA_STATUSCODE_BADWRITENOTSUPPORTED
#define OpcUa_GoodCallAgain UA_STATUSCODE_GOODCALLAGAIN
#define OpcUa_GoodClamped UA_STATUSCODE_GOODCLAMPED
#define OpcUa_GoodCommunicationEvent UA_STATUSCODE_GOODCOMMUNICATIONEVENT
#define OpcUa_GoodCompletesAsynchronously UA_STATUSCODE_GOODCOMPLETESASYNCHRONOUSLY
#define OpcUa_GoodDataIgnored UA_STATUSCODE_GOODDATAIGNORED
#define OpcUa_GoodDependentValueChanged UA_STATUSCODE_GOODDEPENDENTVALUECHANGED
#define OpcUa_GoodEdited UA_STATUSCODE_GOODEDITED
#define OpcUa_GoodEntryInserted UA_STATUSCODE_GOODENTRYINSERTED
#define OpcUa_GoodEntryReplaced UA_STATUSCODE_GOODENTRYREPLACED
#define OpcUa_GoodLocalOverride UA_STATUSCODE_GOODLOCALOVERRIDE
#define OpcUa_GoodMoreData UA_STATUSCODE_GOODMOREDATA
#define OpcUa_GoodNoData UA_STATUSCODE_GOODNODATA
#define OpcUa_GoodNonCriticalTimeout UA_STATUSCODE_GOODNONCRITICALTIMEOUT
#define OpcUa_GoodOverload UA_STATUSCODE_GOODOVERLOAD
#define OpcUa_GoodPostActionFailed UA_STATUSCODE_GOODPOSTACTIONFAILED
#define OpcUa_GoodResultsMayBeIncomplete UA_STATUSCODE_GOODRESULTSMAYBEINCOMPLETE
#define OpcUa_GoodRetransmissionQueueNotSupported UA_STATUSCODE_GOODRETRANSMISSIONQUEUENOTSUPPORTED
#define OpcUa_GoodShutdownEvent UA_STATUSCODE_GOODSHUTDOWNEVENT
#define OpcUa_GoodSubscriptionTransferred UA_STATUSCODE_GOODSUBSCRIPTIONTRANSFERRED
#define OpcUa_UncertainDataSubNormal UA_STATUSCODE_UNCERTAINDATASUBNORMAL
#define OpcUa_UncertainDependentValueChanged UA_STATUSCODE_UNCERTAINDEPENDENTVALUECHANGED
#define OpcUa_UncertainDominantValueChanged UA_STATUSCODE_UNCERTAINDOMINANTVALUECHANGED
#define OpcUa_UncertainEngineeringUnitsExceeded UA_STATUSCODE_UNCERTAINENGINEERINGUNITSEXCEEDED
#define OpcUa_UncertainLastUsableValue UA_STATUSCODE_UNCERTAINLASTUSABLEVALUE
#define OpcUa_UncertainNoCommunicationLastUsableValue UA_STATUSCODE_UNCERTAINNOCOMMUNICATIONLASTUSABLEVALUE
#define OpcUa_UncertainNotAllNodesAvailable UA_STATUSCODE_UNCERTAINNOTALLNODESAVAILABLE
#define OpcUa_UncertainReferenceNotDeleted UA_STATUSCODE_UNCERTAINREFERENCENOTDELETED
#define OpcUa_UncertainReferenceOutOfServer UA_STATUSCODE_UNCERTAINREFERENCEOUTOFSERVER
#define OpcUa_UncertainSensorNotAccurate UA_STATUSCODE_UNCERTAINSENSORNOTACCURATE
#define OpcUa_UncertainSubNormal UA_STATUSCODE_UNCERTAINSUBNORMAL
#define OpcUa_UncertainSubstituteValue UA_STATUSCODE_UNCERTAINSUBSTITUTEVALUE

typedef OpcUa_UInt32 OpcUa_StatusCode;

struct StatusCodeDescription {
        		OpcUa_StatusCode statusCode;
        		const std::string description;
        	};

class UaStatus
{
public:

    UaStatus (OpcUa_StatusCode s): m_status(s) {} // from status code
    UaStatus(): m_status(OpcUa_Bad) {} // by default, initialize to Bad

    const UaStatus& operator=(OpcUa_StatusCode status) { m_status = status; return *this; }

    bool isGood() const { return m_status == UA_STATUSCODE_GOOD; }
    bool isNotGood() const { return !isGood(); }
    bool isBad() const;
    bool isUncertain() const;
    UaString toString() const;

    OpcUa_StatusCode statusCode() const { return m_status; }
    OpcUa_StatusCode code() const { return m_status; }
    operator UA_StatusCode() const { return (UA_StatusCode)m_status; }
    static std::vector<StatusCodeDescription> s_statusCodeDescriptions;

private:
    OpcUa_StatusCode m_status;

};

#endif //__STATUSCODE_H__
